/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root';
import { Route as layoutRouteImport } from './routes/layout';
import { Route as indexRouteImport } from './routes/index';
import { Route as querySuspenseStatesDotrouteRouteImport } from './routes/query-suspense/states.route';
import { Route as apolloSuspenseFilmsDotrouteRouteImport } from './routes/apollo-suspense/films.route';
import { Route as querySuspenseCitiesDotrouteRouteImport } from './routes/query-suspense/cities.route';
import { Route as apolloSuspenseFilmDotrouteRouteImport } from './routes/apollo-suspense/film.route';
import { Route as querySuspenseStatesIndexDotrouteRouteImport } from './routes/query-suspense/states-index.route';
import { Route as apolloSuspenseFilmsIndexDotrouteRouteImport } from './routes/apollo-suspense/films-index.route';

const layoutRoute = layoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRoute,
} as any);
const querySuspenseStatesDotrouteRoute =
  querySuspenseStatesDotrouteRouteImport.update({
    id: '/states',
    path: '/states',
    getParentRoute: () => layoutRoute,
  } as any);
const apolloSuspenseFilmsDotrouteRoute =
  apolloSuspenseFilmsDotrouteRouteImport.update({
    id: '/films',
    path: '/films',
    getParentRoute: () => layoutRoute,
  } as any);
const querySuspenseCitiesDotrouteRoute =
  querySuspenseCitiesDotrouteRouteImport.update({
    id: '/$state',
    path: '/$state',
    getParentRoute: () => querySuspenseStatesDotrouteRoute,
  } as any);
const apolloSuspenseFilmDotrouteRoute =
  apolloSuspenseFilmDotrouteRouteImport.update({
    id: '/$filmId',
    path: '/$filmId',
    getParentRoute: () => apolloSuspenseFilmsDotrouteRoute,
  } as any);
const querySuspenseStatesIndexDotrouteRoute =
  querySuspenseStatesIndexDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => querySuspenseStatesDotrouteRoute,
  } as any);
const apolloSuspenseFilmsIndexDotrouteRoute =
  apolloSuspenseFilmsIndexDotrouteRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => apolloSuspenseFilmsDotrouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/films': typeof apolloSuspenseFilmsDotrouteRouteWithChildren;
  '/states': typeof querySuspenseStatesDotrouteRouteWithChildren;
  '/': typeof indexRoute;
  '/films/': typeof apolloSuspenseFilmsIndexDotrouteRoute;
  '/states/': typeof querySuspenseStatesIndexDotrouteRoute;
  '/films/$filmId': typeof apolloSuspenseFilmDotrouteRoute;
  '/states/$state': typeof querySuspenseCitiesDotrouteRoute;
}
export interface FileRoutesByTo {
  '/': typeof indexRoute;
  '/films': typeof apolloSuspenseFilmsIndexDotrouteRoute;
  '/states': typeof querySuspenseStatesIndexDotrouteRoute;
  '/films/$filmId': typeof apolloSuspenseFilmDotrouteRoute;
  '/states/$state': typeof querySuspenseCitiesDotrouteRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_layout': typeof layoutRouteWithChildren;
  '/_layout/films': typeof apolloSuspenseFilmsDotrouteRouteWithChildren;
  '/_layout/states': typeof querySuspenseStatesDotrouteRouteWithChildren;
  '/_layout/': typeof indexRoute;
  '/_layout/films/': typeof apolloSuspenseFilmsIndexDotrouteRoute;
  '/_layout/states/': typeof querySuspenseStatesIndexDotrouteRoute;
  '/_layout/films/$filmId': typeof apolloSuspenseFilmDotrouteRoute;
  '/_layout/states/$state': typeof querySuspenseCitiesDotrouteRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/films'
    | '/states'
    | '/'
    | '/films/'
    | '/states/'
    | '/films/$filmId'
    | '/states/$state';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/films' | '/states' | '/films/$filmId' | '/states/$state';
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/films'
    | '/_layout/states'
    | '/_layout/'
    | '/_layout/films/'
    | '/_layout/states/'
    | '/_layout/films/$filmId'
    | '/_layout/states/$state';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  layoutRoute: typeof layoutRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof layoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_layout/states': {
      id: '/_layout/states';
      path: '/states';
      fullPath: '/states';
      preLoaderRoute: typeof querySuspenseStatesDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_layout/films': {
      id: '/_layout/films';
      path: '/films';
      fullPath: '/films';
      preLoaderRoute: typeof apolloSuspenseFilmsDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_layout/states/$state': {
      id: '/_layout/states/$state';
      path: '/$state';
      fullPath: '/states/$state';
      preLoaderRoute: typeof querySuspenseCitiesDotrouteRouteImport;
      parentRoute: typeof querySuspenseStatesDotrouteRoute;
    };
    '/_layout/films/$filmId': {
      id: '/_layout/films/$filmId';
      path: '/$filmId';
      fullPath: '/films/$filmId';
      preLoaderRoute: typeof apolloSuspenseFilmDotrouteRouteImport;
      parentRoute: typeof apolloSuspenseFilmsDotrouteRoute;
    };
    '/_layout/states/': {
      id: '/_layout/states/';
      path: '/';
      fullPath: '/states/';
      preLoaderRoute: typeof querySuspenseStatesIndexDotrouteRouteImport;
      parentRoute: typeof querySuspenseStatesDotrouteRoute;
    };
    '/_layout/films/': {
      id: '/_layout/films/';
      path: '/';
      fullPath: '/films/';
      preLoaderRoute: typeof apolloSuspenseFilmsIndexDotrouteRouteImport;
      parentRoute: typeof apolloSuspenseFilmsDotrouteRoute;
    };
  }
}

interface apolloSuspenseFilmsDotrouteRouteChildren {
  apolloSuspenseFilmsIndexDotrouteRoute: typeof apolloSuspenseFilmsIndexDotrouteRoute;
  apolloSuspenseFilmDotrouteRoute: typeof apolloSuspenseFilmDotrouteRoute;
}

const apolloSuspenseFilmsDotrouteRouteChildren: apolloSuspenseFilmsDotrouteRouteChildren =
  {
    apolloSuspenseFilmsIndexDotrouteRoute:
      apolloSuspenseFilmsIndexDotrouteRoute,
    apolloSuspenseFilmDotrouteRoute: apolloSuspenseFilmDotrouteRoute,
  };

const apolloSuspenseFilmsDotrouteRouteWithChildren =
  apolloSuspenseFilmsDotrouteRoute._addFileChildren(
    apolloSuspenseFilmsDotrouteRouteChildren,
  );

interface querySuspenseStatesDotrouteRouteChildren {
  querySuspenseStatesIndexDotrouteRoute: typeof querySuspenseStatesIndexDotrouteRoute;
  querySuspenseCitiesDotrouteRoute: typeof querySuspenseCitiesDotrouteRoute;
}

const querySuspenseStatesDotrouteRouteChildren: querySuspenseStatesDotrouteRouteChildren =
  {
    querySuspenseStatesIndexDotrouteRoute:
      querySuspenseStatesIndexDotrouteRoute,
    querySuspenseCitiesDotrouteRoute: querySuspenseCitiesDotrouteRoute,
  };

const querySuspenseStatesDotrouteRouteWithChildren =
  querySuspenseStatesDotrouteRoute._addFileChildren(
    querySuspenseStatesDotrouteRouteChildren,
  );

interface layoutRouteChildren {
  apolloSuspenseFilmsDotrouteRoute: typeof apolloSuspenseFilmsDotrouteRouteWithChildren;
  querySuspenseStatesDotrouteRoute: typeof querySuspenseStatesDotrouteRouteWithChildren;
  indexRoute: typeof indexRoute;
}

const layoutRouteChildren: layoutRouteChildren = {
  apolloSuspenseFilmsDotrouteRoute:
    apolloSuspenseFilmsDotrouteRouteWithChildren,
  querySuspenseStatesDotrouteRoute:
    querySuspenseStatesDotrouteRouteWithChildren,
  indexRoute: indexRoute,
};

const layoutRouteWithChildren =
  layoutRoute._addFileChildren(layoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  layoutRoute: layoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
