/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/root';
import { Route as layoutRouteImport } from './routes/layout';
import { Route as indexRouteImport } from './routes/index';
import { Route as querySuspenseQuerySuspenseDotrouteRouteImport } from './routes/query-suspense/query-suspense.route';
import { Route as floorballFloorballDotrouteRouteImport } from './routes/floorball/floorball.route';
import { Route as apolloSuspenseApolloSuspenseDotrouteRouteImport } from './routes/apollo-suspense/apollo-suspense.route';

const layoutRoute = layoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRoute,
} as any);
const querySuspenseQuerySuspenseDotrouteRoute =
  querySuspenseQuerySuspenseDotrouteRouteImport.update({
    id: '/query-suspense',
    path: '/query-suspense',
    getParentRoute: () => layoutRoute,
  } as any);
const floorballFloorballDotrouteRoute =
  floorballFloorballDotrouteRouteImport.update({
    id: '/floorball',
    path: '/floorball',
    getParentRoute: () => layoutRoute,
  } as any);
const apolloSuspenseApolloSuspenseDotrouteRoute =
  apolloSuspenseApolloSuspenseDotrouteRouteImport.update({
    id: '/apollo-suspense',
    path: '/apollo-suspense',
    getParentRoute: () => layoutRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/apollo-suspense': typeof apolloSuspenseApolloSuspenseDotrouteRoute;
  '/floorball': typeof floorballFloorballDotrouteRoute;
  '/query-suspense': typeof querySuspenseQuerySuspenseDotrouteRoute;
  '/': typeof indexRoute;
}
export interface FileRoutesByTo {
  '/apollo-suspense': typeof apolloSuspenseApolloSuspenseDotrouteRoute;
  '/floorball': typeof floorballFloorballDotrouteRoute;
  '/query-suspense': typeof querySuspenseQuerySuspenseDotrouteRoute;
  '/': typeof indexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_layout': typeof layoutRouteWithChildren;
  '/_layout/apollo-suspense': typeof apolloSuspenseApolloSuspenseDotrouteRoute;
  '/_layout/floorball': typeof floorballFloorballDotrouteRoute;
  '/_layout/query-suspense': typeof querySuspenseQuerySuspenseDotrouteRoute;
  '/_layout/': typeof indexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/apollo-suspense' | '/floorball' | '/query-suspense' | '/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/apollo-suspense' | '/floorball' | '/query-suspense' | '/';
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/apollo-suspense'
    | '/_layout/floorball'
    | '/_layout/query-suspense'
    | '/_layout/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  layoutRoute: typeof layoutRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof layoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_layout/query-suspense': {
      id: '/_layout/query-suspense';
      path: '/query-suspense';
      fullPath: '/query-suspense';
      preLoaderRoute: typeof querySuspenseQuerySuspenseDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_layout/floorball': {
      id: '/_layout/floorball';
      path: '/floorball';
      fullPath: '/floorball';
      preLoaderRoute: typeof floorballFloorballDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
    '/_layout/apollo-suspense': {
      id: '/_layout/apollo-suspense';
      path: '/apollo-suspense';
      fullPath: '/apollo-suspense';
      preLoaderRoute: typeof apolloSuspenseApolloSuspenseDotrouteRouteImport;
      parentRoute: typeof layoutRoute;
    };
  }
}

interface layoutRouteChildren {
  apolloSuspenseApolloSuspenseDotrouteRoute: typeof apolloSuspenseApolloSuspenseDotrouteRoute;
  floorballFloorballDotrouteRoute: typeof floorballFloorballDotrouteRoute;
  querySuspenseQuerySuspenseDotrouteRoute: typeof querySuspenseQuerySuspenseDotrouteRoute;
  indexRoute: typeof indexRoute;
}

const layoutRouteChildren: layoutRouteChildren = {
  apolloSuspenseApolloSuspenseDotrouteRoute:
    apolloSuspenseApolloSuspenseDotrouteRoute,
  floorballFloorballDotrouteRoute: floorballFloorballDotrouteRoute,
  querySuspenseQuerySuspenseDotrouteRoute:
    querySuspenseQuerySuspenseDotrouteRoute,
  indexRoute: indexRoute,
};

const layoutRouteWithChildren =
  layoutRoute._addFileChildren(layoutRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  layoutRoute: layoutRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
